services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports: ["2181:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  create-topics:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [kafka]
    entrypoint: ["/bin/bash","-c"]
    command: >
      "
      kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --topic transactions --partitions 3 --replication-factor 1 &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --topic scores --partitions 3 --replication-factor 1
      "
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fraud}
      POSTGRES_USER: ${POSTGRES_USER:-fraud}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fraud}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  scorer:
    build: ./scorer
    depends_on: [create-topics]
    environment:
      KAFKA_BOOTSTRAP: kafka:29092
      INPUT_TOPIC: transactions
      OUTPUT_TOPIC: scores
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
  
  sink:
    build: ./sink
    depends_on: [postgres, create-topics]
    environment:
      KAFKA_BOOTSTRAP: kafka:29092
      INPUT_TOPIC: scores
      PG_DSN: postgresql://fraud:fraud@postgres:5432/fraud
    restart: unless-stopped

  ui:
    build: ./ui
    depends_on: [postgres]
    environment:
      PG_DSN: postgresql://fraud:fraud@postgres:5432/fraud
    ports: ["8501:8501"]
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on: [kafka]
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: 'true'

volumes:
  pgdata: